### ISSUE TITLE
Doesn't work on Linux

### ISSUE THREAD

**Issue by damouse** [aciidb0mb3r/SwiftMQTT#51]
Doesn't work on Linux with Swift version 4.2. 

```
/app/.build/checkouts/SwiftMQTT/SwiftMQTT/SwiftMQTT/MQTTSessionStream.swift:31:9: error: type 'Stream' has no member 'getStreamsToHost'
        Stream.getStreamsToHost(withName: host, port: Int(port), inputStream: &inputStream, outputStream: &outputStream)
        ^~~~~~ ~~~~~~~~~~~~~~~~
/app/.build/checkouts/SwiftMQTT/SwiftMQTT/SwiftMQTT/MQTTSessionStream.swift:58:42: error: cannot convert value of type 'String' to expected argument type 'AnyObject?'
                inputStream?.setProperty(securityLevel, forKey: .socketSecurityLevelKey)

```
